language: python
python:
  - 3.4
  - 3.5
  - nightly
env:
  - DJANGO_VERSION=1.8.9
  - DJANGO_VERSION=1.9.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script: python src/runtests.py
matrix:
  allow_failures:
    - python: nightly
notifications:
  email:
    on_success: change
    on_failure: change